
services:

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
    depends_on:
      - wordpress
    ports:
#      - "443:443"
      - "4443:4443"
    networks:
      - inception
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - .env
    restart: always

  mariadb:
    build:
      context: requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file:
      - .env
    restart: always

networks:
  inception:
    name: inception
    driver: bridge


volumes:
  mariadb_v:
  wordpress_v:


